output: 'tmp' 
prob_name: 'sch'
n_obj: 2
n_var: 1
xl: -100
xu: 100
sld_n_part: 249
n_eval: 10000
T: 20
delta: 0.9
nr: 2
alpha : 1.e-05
betal : 0.1
betau : 1.9
etam : 20
alpha for param : 0.1
beta for param : 1.0
n_step : 20
wag : 120
rate_evol : 0.8
rate_update_weight : 0.05