output: '../../../Volumes/HD-PNFU3/temp_exp/tmp' 
prob_name: 'dtlz1'
n_obj: 2
n_var: 100
xl: 0
xu: 1
decomp_method: 'sld'
sld_n_part: 12
n_eval: 30000
T: 100
delta: 0.9
nr: 2
alpha : 1.e-05
beta : 0.3
etam : 20
